language: bash
sudo: false

addons:
  apt:
    #sources:
    #  - debian-sid
    packages:
      - libxml2-utils
      - xsltproc
      - docbook
      - docbook-xml
      - shellcheck
script:
  - ./ci/build.sh
notifications:
  email: false
